name: dafluta_example
description: Example code for the dafluta library.
version: 5.2.0
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter