name: dafluta_example
description: Example code for the dafluta library.
version: 4.5.1
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter