name: dafluta_example
description: Example code for the dafluta library.
version: 3.9.0
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter