name: dafluta_example
description: Example code for the dafluta library.
version: 5.6.0
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
