name: dafluta
description: A set of Flutter util classes and methods that are commonly used in projects.
version: 3.2.0
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

  meta: ^1.7.0
  collection: ^1.16.0
  flutter_lints: ^2.0.1