name: dafluta
description: A set of Flutter utils
version: 0.0.5
author: Mauricio Togneri <mauricio.togneri@gmail.com>
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  http: ^0.12.0+2

dev_dependencies:

  flutter_test:
    sdk: flutter

  meta: ^1.1.6  