name: dafluta
description: A set of Flutter util classes and methods that are commonly used in projects.
version: 5.2.0
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  meta: ^1.10.0
  collection: ^1.18.0
  flutter_lints: ^3.0.1