name: dafluta
description: A set of Flutter utils
version: 0.0.1
author: Mauricio Togneri <mauricio.togneri@gmail.com>
homepage: https://mauriciotogneri.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter