name: dafluta
description: A set of Flutter util classes and methods that are commonly used in projects.
version: 2.9.0
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

  meta: ^1.3.0
  collection: ^1.15.0