name: dafluta
description: A set of Flutter util classes and methods that are commonly used in projects.
version: 1.8.1
author: Mauricio Togneri <mauricio.togneri@gmail.com>
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

  meta: ^1.1.6
  collection: ^1.14.11