name: dafluta
description: A set of Flutter widgets and util classes that are commonly used in projects.
version: 5.5.1
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
