name: dafluta
description: A set of Flutter util classes and methods that are commonly used in projects.
version: 1.2.0
author: Mauricio Togneri <mauricio.togneri@gmail.com>
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  http: ^0.12.0+2
  path: ^1.6.2

dev_dependencies:

  flutter_test:
    sdk: flutter

  meta: ^1.1.6