name: dafluta
description: A set of Flutter util classes and methods that are commonly used in projects.
version: 4.3.1
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

  meta: ^1.8.0
  collection: ^1.16.0
  flutter_lints: ^2.0.1