name: dafluta
description: A set of Flutter widgets and util classes that are commonly used in projects.
version: 5.6.0
homepage: https://github.com/mauriciotogneri/dafluta

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
