typedef Int = int;
typedef Integer = int;
typedef Float = double;
typedef Double = double;
typedef Number = num;
typedef Bool = bool;
typedef Boolean = bool;
typedef JsonObject = Map<String, dynamic>;
typedef JsonArray = List<JsonObject>;
